baseURL = "https://carefullaurent.cc/"
languageCode = "en-us"
title = "Careful, Laurent"
theme = "hyde"
disqusShortname = "careful-blog"
[params]
    description = "an absurd mini-fiction blog about escaping your head"
    layoutReverse = true
[menu]
  [[menu.main]]
    identifier = "list"
    name = "List"
    url = "/number"
  [[menu.main]]
    identifier = "twitter"
    name = "Tweets"
    url = "https://twitter.com/aninternetof"
