baseURL = "https://brady.fyi/"
languageCode = "en-us"
title = "Brady Hurlburt"
theme = "hyde"
disqusShortname = "careful-blog"
[params]
    description = "I am interested in education and code."
    layoutReverse = true
[menu]
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = -110
  [[menu.main]]
    identifier = "softare"
    name = "software"
    url = "/projects/"
    weight = -100
  [[menu.main]]
    identifier = "rovercode"
    name = "rovercode"
    url = "https://rovercode.com"
    weight = -90
  [[menu.main]]
    identifier = "twitter"
    name = "Tweetz"
    url = "https://twitter.com/aninternetof"
    weight = -80
